export const GET_INTERVIEW_QUESTIONS  = "GET_INTERVIEW_QUESTIONS"
export const GET_INTERVIEW_STATUS  = "GET_INTERVIEW_STATUS"
export const POST_EMPLOYEE_APPROVE  = "POST_EMPLOYEE_APPROVE"
export const GET_EMPLOYEE_APPROVE ="GET_EMPLOYEE_APPROVE"