
export const GET_INTERVIEWERS = "GET_INTERVIEWERS"
export const GET_DESIGNATION = "GET_DESIGNATION"
export const POST_EMPLOYEE_APPROVE = "POST_EMPLOYEE_APPROVE"
export const GET_EMPLOYEE_APPROVE = "GET_EMPLOYEE_APPROVE"
export const POST_INTERVIEW_QUESTIONS = "POST_INTERVIEW_QUESTIONS"
export const GET_EMPLOYEEFORM_ID = "GET_EMPLOYEEFORM_ID"

// Resume
export const INSERT_RESUME = "INSERT_RESUME"
//Details-->Employee and Candidate
export const GET_CANDIDATES_DETAILS = "GET_CANDIDATES_DETAILS"
export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS"
// masterDropdrop
export const GET_RESOURCE_TYPE = "GET_RESOURCE_TYPE";
export const GET_INSTITUTE = "GET_INSTITUTE";
export const GET_SPECIAL_INTEREST = "GET_SPECIAL_INTEREST";
export const GET_STATE = "GET_STATE";
export const GET_CITY = "GET_CITY";
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_SKILLS = "GET_SKILLS"
export const GET_TRAITS = "GET_TRAITS"
export const GET_CERTIFICATION = "GET_CERTIFICATION"
export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT"
export const GET_SPECILIZATION = "GET_SPECILIZATION"
export const GET_CAPABILITY = "GET_CAPABILITY"
export const GET_TALENTS = "GET_TALENTS"
export const GET_STATUS = "GET_STATUS"
export const GET_QUALIFICATION = "GET_QUALIFICATION"
export const GET_INDUSTRY = "GET_INDUSTRY"
export const GET_PROJECT_SUB_TYPE = "GET_PROJECT_SUB_TYPE"
export const GET_STAGELIST = "GET_STAGELIST";
export const GET_SUB_STAGE = "GET_SUB_STAGE";
export const GET_INTERVIEW_STATUS = "GET_INTERVIEW_STATUS"
export const GET_DESIGNATION_LIST = "GET_DESIGNATION_LIST"
export const GET_DEPARTMENT = "GET_DEPARTMENT"
export const GET_INTERVIEWERS_LIST = "GET_INTERVIEWERS_LIST"
export const GET_COURT_LOCATION = "GET_COURT_LOCATION"
export const GET_TRADE_MARK_STATUS = "GET_TRADE_MARK_STATUS"
export const GET_CASE_TYPE = "GET_CASE_TYPE"
export const GET_SUB_CASE_TYPE = "GET_SUB_CASE_TYPE"
// ResumeSearch

export const GET_RESUMESEARCH_ROWDATA = "GET_RESUMESEARCH_ROWDATA"

// Project Search

export const GET_CLIENT_TYPE = "GET_CLIENT_TYPE";
export const GET_CLIENT = "GET_CLIENT";
export const GET_PROJECT_TYPE = "GET_PROJECT_TYPE";
export const GET_PROCESS_TYPE = "GET_PROCESS_TYPE";
export const GET_PROJECT_NAME = "GET_PROJECT_NAME";
export const GET_BILLABLE_TYPE = "GET_BILLABLE_TYPE";

export const GET_PROJECT_SEARCH_TABLEDATA = "GET_PROJECT_SEARCH_TABLEDATA";

//Project form create
export const GET_FILING_TYPE = "GET_FILING_TYPE";
// AddClient
export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_DOCUMENT = "ADD_CLIENT_DOCUMENT";
export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_PROJECT_COST_RANGE = "GET_PROJECT_COST_RANGE";
export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const INSERT_IPPROJECT = "INSERT_IPPROJECT";


// HrSearch
export const GET_HRSEARCH_ROWDATA = "GET_HRSEARCH_ROWDATA"
export const GET_INTERVIEW_APPROVER = "GET_INTERVIEW_APPROVER"

// HRTodoList
export const GET_HRTODOLIST = "GET_HRTODOLIST";
//HR-->Interview
export const GET_INTERVIEW_QUESTIONS = "GET_INTERVIEW_QUESTIONS"
export const GET_SELECTED_CANDIDATES = "GET_SELECTED_CANDIDATES";
export const INTERVIEWAPPROVER_TABLE_DATA = "INTERVIEWAPPROVER_TABLE_DATA"

// StageMaster , ,
export const GET_STAGEMASTER_TABLEDATA = "GET_STAGEMASTER_TABLEDATA";
export const INSERT_STAGEMASTER = "INSERT_STAGEMASTER";
// VariableRateMaster
export const GET_VARIABLERATE_TABLE_DATA = "GET_VARIABLERATE_TABLE_DATA";
export const INSERT_VARIABLERATE = "INSERT_VARIABLERATE";
export const SEARCH_VARIABLERATE = "SEARCH_VARIABLERATE";
// ProjectsFillingFinal
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";

//TASK & TIMESHEET

export const GET_ACTIVITY ="GET_ACTIVITY";
export const GET_TAG ="GET_TAG";
export const GET_PRIORITY ="GET_PRIORITY";
export const INSERT_TASK ="INSERT_TASK";
export const INSERT_ADHOC_TASK ="INSERT_ADHOC_TASK";
export const GET_LOCATION ="GET_LOCATION";
export const GET_ASSIGN_TO ="GET_ASSIGN_TO";
export const GET_SUBACTIVITY ="GET_SUBACTIVITY";


//Litigation
export const GET_LITIGATION ="GET_LITIGATION";
export const INSERT_LITIGATION ="INSERT_LITIGATION";
export const UPDATE_LITIGATION_DETAILS ="UPDATE_LITIGATION_DETAILS";

// Leave Form 

export const GET_LEAVETYPE ="GET_LEAVETYPE";

